//! Deterministic Markdown generator for the Lattice Zola site.
#![allow(clippy::format_push_string)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::semicolon_if_nothing_returned)]

use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::{Path, PathBuf},
};

use clap::{Parser, Subcommand};
use lattice_cli::CommandDocumentation;
use lattice_model::ErrorCode;
use serde_json::Value;
use thiserror::Error;

const GENERATED_ROOT: &str = "content/reference/generated";
const GENERATED_NOTICE: &str = "<!-- GENERATED BY lattice-docgen. DO NOT EDIT MANUALLY. -->\n";

#[derive(Debug, Parser)]
#[command(
    name = "lattice-docgen",
    version,
    about = "Generate deterministic Lattice reference documentation"
)]
struct Arguments {
    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Generate committed reference Markdown under docs/content/reference/generated.
    Generate {
        #[arg(long)]
        docs_root: Option<PathBuf>,
    },
    /// Verify committed generated Markdown is current without writing files.
    Check {
        #[arg(long)]
        docs_root: Option<PathBuf>,
    },
}

#[derive(Debug, Error)]
enum GeneratorError {
    #[error("I/O error at {path}: {source}")]
    Io { path: PathBuf, source: std::io::Error },
    #[error("metadata serialization failed: {0}")]
    Json(#[from] serde_json::Error),
    #[error("generated documentation is stale: {0}")]
    Drift(String),
    #[error("MCP metadata unavailable: {0}")]
    McpMetadata(String),
}

fn main() -> Result<(), GeneratorError> {
    let arguments = Arguments::parse();
    let command = arguments.command.unwrap_or(Command::Generate { docs_root: None });
    match command {
        Command::Generate { docs_root } => generate(&resolve_docs_root(docs_root)?)?,
        Command::Check { docs_root } => check(&resolve_docs_root(docs_root)?)?,
    }
    Ok(())
}

fn resolve_docs_root(explicit: Option<PathBuf>) -> Result<PathBuf, GeneratorError> {
    if let Some(root) = explicit {
        return Ok(root);
    }
    let current = env::current_dir()
        .map_err(|source| GeneratorError::Io { path: PathBuf::from("."), source })?;
    if current.join("content").is_dir() && current.join("config.toml").is_file() {
        return Ok(current);
    }
    Ok(current.join("docs"))
}

fn generate(docs_root: &Path) -> Result<(), GeneratorError> {
    let files = render_all()?;
    let generated_root = docs_root.join(GENERATED_ROOT);
    fs::create_dir_all(&generated_root)
        .map_err(|source| GeneratorError::Io { path: generated_root.clone(), source })?;

    let expected = files.keys().cloned().collect::<BTreeSet<_>>();
    for (relative, contents) in &files {
        let path = generated_root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|source| GeneratorError::Io { path: parent.to_path_buf(), source })?;
        }
        fs::write(&path, contents).map_err(|source| GeneratorError::Io { path, source })?;
    }
    for existing in markdown_files(&generated_root)? {
        let relative = existing
            .strip_prefix(&generated_root)
            .map_err(|_| GeneratorError::Drift(existing.display().to_string()))?
            .to_path_buf();
        if !expected.contains(&relative) {
            fs::remove_file(&existing)
                .map_err(|source| GeneratorError::Io { path: existing, source })?;
        }
    }
    println!(
        "generated {} deterministic reference pages under {}",
        files.len(),
        generated_root.display()
    );
    Ok(())
}

fn check(docs_root: &Path) -> Result<(), GeneratorError> {
    let files = render_all()?;
    let generated_root = docs_root.join(GENERATED_ROOT);
    let mut differences = Vec::new();
    for (relative, expected) in &files {
        let path = generated_root.join(relative);
        match fs::read_to_string(&path) {
            Ok(actual) if actual == *expected => {}
            Ok(_) => differences.push(format!("changed: {}", relative.display())),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                differences.push(format!("missing: {}", relative.display()))
            }
            Err(source) => return Err(GeneratorError::Io { path, source }),
        }
    }
    for existing in markdown_files(&generated_root)? {
        let relative = existing
            .strip_prefix(&generated_root)
            .map_err(|_| GeneratorError::Drift(existing.display().to_string()))?
            .to_path_buf();
        if !files.contains_key(&relative) {
            differences.push(format!("unexpected: {}", relative.display()));
        }
    }
    if differences.is_empty() {
        println!("generated reference documentation is current");
        Ok(())
    } else {
        Err(GeneratorError::Drift(differences.join(", ")))
    }
}

fn markdown_files(root: &Path) -> Result<Vec<PathBuf>, GeneratorError> {
    let mut files = Vec::new();
    if !root.is_dir() {
        return Ok(files);
    }
    visit_markdown(root, &mut files)?;
    files.sort();
    Ok(files)
}

fn visit_markdown(root: &Path, files: &mut Vec<PathBuf>) -> Result<(), GeneratorError> {
    let entries = fs::read_dir(root)
        .map_err(|source| GeneratorError::Io { path: root.to_path_buf(), source })?;
    for entry in entries {
        let entry =
            entry.map_err(|source| GeneratorError::Io { path: root.to_path_buf(), source })?;
        let path = entry.path();
        if path.is_dir() {
            visit_markdown(&path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "md") {
            files.push(path);
        }
    }
    Ok(())
}

fn render_all() -> Result<BTreeMap<PathBuf, String>, GeneratorError> {
    let mut files = BTreeMap::new();
    render_cli(&mut files);
    render_mcp(&mut files)?;
    render_capabilities(&mut files)?;
    render_providers(&mut files)?;
    render_errors(&mut files);
    render_configuration(&mut files);
    render_reference_index(&mut files);
    Ok(files)
}

fn render_cli(files: &mut BTreeMap<PathBuf, String>) {
    let commands = lattice_cli::command_documentation();
    let mut index = page(
        "CLI Reference",
        "Generated from the structured native CLI command contract.",
        "lattice-cli",
    );
    index.push_str("## Commands\n\n");
    for command in &commands {
        let slug = slug(&command.path);
        index.push_str(&format!("- [{}]({}/) — {}\n", command.path, slug, command.description));
        files.insert(PathBuf::from("cli").join(&slug).join("_index.md"), render_cli_page(command));
    }
    files.insert(PathBuf::from("cli/_index.md"), index);
}

fn render_cli_page(command: &CommandDocumentation) -> String {
    let mut page = page(&command.path, &command.description, "lattice-cli");
    page.push_str(&format!("## Usage\n\n```text\n{}\n```\n\n", command.usage));
    if !command.arguments.is_empty() {
        page.push_str("## Arguments and options\n\n| Name | Kind | Required | Default | Description |\n| --- | --- | --- | --- | --- |\n");
        for argument in &command.arguments {
            page.push_str(&format!(
                "| `{}` | {} | {} | {} | {} |\n",
                argument.name,
                argument.kind,
                if argument.required { "yes" } else { "no" },
                argument.default.as_deref().unwrap_or("—"),
                markdown(&argument.description)
            ));
        }
        page.push('\n');
    }
    if !command.examples.is_empty() {
        page.push_str("## Examples\n\n");
        for example in &command.examples {
            page.push_str(&format!("```sh\n{}\n```\n\n", example));
        }
    }
    page.push_str("Exit behavior and errors are reported as structured JSON when the command succeeds or fails.\n");
    page
}

fn render_mcp(files: &mut BTreeMap<PathBuf, String>) -> Result<(), GeneratorError> {
    let tools = lattice_mcp::northbound_tool_documentation()
        .map_err(|error| GeneratorError::McpMetadata(error.to_string()))?;
    let mut index = page(
        "MCP Tools",
        "Generated from the northbound Lattice MCP tool registry.",
        "lattice-mcp",
    );
    index.push_str("## Tools\n\n");
    for tool in &tools {
        let slug = slug(&tool.name);
        index.push_str(&format!(
            "- [{}]({}/) — {}\n",
            tool.name,
            slug,
            markdown(&tool.description)
        ));
        let mut output =
            page(&format!("MCP Tool: {}", tool.name), &tool.description, "lattice-mcp");
        output.push_str(&format!("## Purpose\n\n{}\n\n", markdown(&tool.description)));
        output.push_str("## Input schema\n\n```json\n");
        output.push_str(&serde_json::to_string_pretty(&tool.input_schema)?);
        output.push_str("\n```\n\n");
        output.push_str("## Output schema\n\n```json\n");
        output.push_str(&serde_json::to_string_pretty(&tool.output_schema)?);
        output.push_str("\n```\n\n");
        output.push_str("## Safety\n\nThis northbound operation is subject to Lattice policy and records an operation-level audit entry. Provider tools are discovered separately through progressive tool search.\n");
        files.insert(PathBuf::from("mcp/tools").join(&slug).join("_index.md"), output);
    }
    files.insert(PathBuf::from("mcp/_index.md"), index);
    Ok(())
}

fn render_capabilities(files: &mut BTreeMap<PathBuf, String>) -> Result<(), GeneratorError> {
    let fabric = lattice_tools::BuiltinToolFabric::from_environments(&[])
        .map_err(|error| GeneratorError::McpMetadata(error.to_string()))?;
    let mut index = page(
        "Capabilities",
        "Generated from the compiled semantic Capability Registry.",
        "lattice-tools",
    );
    index.push_str("## Registered capabilities\n\n| Capability | Meaning | Side effects |\n| --- | --- | --- |\n");
    for definition in fabric.capabilities.list() {
        let slug = slug(definition.id.as_str());
        index.push_str(&format!(
            "| [{}]({}/) | {} | `{}` |\n",
            definition.id,
            slug,
            markdown(&definition.meaning),
            semantics_summary(&definition.side_effects)
        ));
        let mut output = page(definition.id.as_str(), &definition.meaning, "lattice-tools");
        output.push_str(&format!("## Semantic contract\n\n{}\n\n## Input contract\n\n`{}`\n\n## Output contract\n\n`{}`\n\n## Side effects\n\n{}\n", markdown(&definition.meaning), markdown(&definition.input_contract), markdown(&definition.output_contract), semantics_table(&definition.side_effects)));
        output.push_str("## Implementations\n\nImplementations are resolved deterministically from the active provider/tool catalog; an unavailable provider is not treated as an implementation.\n");
        files.insert(PathBuf::from("capabilities").join(&slug).join("_index.md"), output);
    }
    index.push_str("\n## Capability matrix\n\n| Capability | Built-in registry |\n| --- | --- |\n");
    for definition in fabric.capabilities.list() {
        index.push_str(&format!("| `{}` | registered |\n", definition.id));
    }
    files.insert(PathBuf::from("capabilities/_index.md"), index);
    Ok(())
}

fn render_providers(files: &mut BTreeMap<PathBuf, String>) -> Result<(), GeneratorError> {
    let fabric = lattice_tools::BuiltinToolFabric::from_environments(&[])
        .map_err(|error| GeneratorError::McpMetadata(error.to_string()))?;
    let mut index = page(
        "Providers",
        "Generated from the compiled provider registry. Providers remain separate from transient connections.",
        "lattice-tools",
    );
    index.push_str("## Registered providers\n\n| Provider | Kind | Transport | Trust | Availability |\n| --- | --- | --- | --- | --- |\n");
    for provider in fabric.providers.list() {
        let slug = slug(&provider.name);
        index.push_str(&format!(
            "| [{}]({}/) | `{:?}` | `{:?}` | `{:?}` | `{:?}` |\n",
            markdown(&provider.name),
            slug,
            provider.kind,
            provider.transport,
            provider.trust,
            provider.health.status
        ));
        let mut output = page(&provider.name, &provider.health.reason, "lattice-tools");
        output.push_str(&format!("## Provider descriptor\n\n- **Kind:** `{:?}`\n- **Transport:** `{:?}`\n- **Trust:** `{:?}`\n- **Connection state:** `{:?}`\n- **Health:** `{:?}`\n- **Reason:** {}\n", provider.kind, provider.transport, provider.trust, provider.health.connection_state, provider.health.status, markdown(&provider.health.reason)));
        output.push_str("\nProvider credentials and local paths are intentionally omitted from generated documentation.\n");
        files.insert(PathBuf::from("providers").join(&slug).join("_index.md"), output);
    }
    files.insert(PathBuf::from("providers/_index.md"), index);
    Ok(())
}

fn render_errors(files: &mut BTreeMap<PathBuf, String>) {
    let mut index = page(
        "Error Reference",
        "Stable structured error codes emitted by Lattice services and adapters.",
        "lattice-model",
    );
    index.push_str(
        "## Error codes\n\n| Code | Recoverability | Mechanical response |\n| --- | --- | --- |\n",
    );
    for (code, recoverable, action) in error_metadata() {
        let slug = slug(code);
        index.push_str(&format!(
            "| [`{code}`]({slug}/) | {} | {} |\n",
            if recoverable { "usually recoverable" } else { "requires intervention" },
            action
        ));
        let mut output = page(code, action, "lattice-model");
        output.push_str(&format!(
            "## `{code}`\n\n**Recoverability:** {}\n\n**Mechanical action:** {}\n",
            if recoverable { "usually recoverable" } else { "requires intervention" },
            action
        ));
        files.insert(PathBuf::from("errors").join(&slug).join("_index.md"), output);
    }
    files.insert(PathBuf::from("errors/_index.md"), index);
}

fn render_configuration(files: &mut BTreeMap<PathBuf, String>) {
    let mut output = page(
        "Configuration Reference",
        "Configuration reference for native Lattice services.",
        "lattice-docgen",
    );
    output.push_str("## Configuration boundary\n\nLattice keeps provider credentials in the existing secret-store boundary. Documentation examples never contain credentials, local usernames, absolute home paths, or live endpoints.\n\n| Area | Type | Default | Notes |\n| --- | --- | --- | --- |\n| Provider registry | native persisted state | disconnected/lazy | Providers are not all connected at startup. |\n| Studio transport | resolved environment capability | unavailable when unsupported | Platform resolution is authoritative. |\n| MCP | native stdio or Streamable HTTP | local daemon | Northbound catalog remains a small broker surface. |\n| Results | immutable result store | bounded inline response | Large outputs become result references. |\n");
    files.insert(PathBuf::from("config/_index.md"), output);
}

fn render_reference_index(files: &mut BTreeMap<PathBuf, String>) {
    let mut output = page(
        "Generated Reference",
        "Machine-generated Lattice reference material. Each page is derived from compiled metadata.",
        "lattice-docgen",
    );
    output.push_str("## Sections\n\n- [CLI](cli/)\n- [MCP tools](mcp/)\n- [Capabilities](capabilities/)\n- [Providers](providers/)\n- [Errors](errors/)\n- [Configuration](config/)\n");
    files.insert(PathBuf::from("_index.md"), output);
}

fn page(title: &str, description: &str, source: &str) -> String {
    format!(
        "+++\ntitle = \"{}\"\ndescription = \"{}\"\n[extra]\ngenerated = true\nsource = \"{}\"\n+++\n\n{GENERATED_NOTICE}\n# {}\n\n",
        toml_escape(title),
        toml_escape(description),
        toml_escape(source),
        markdown(title)
    )
}

fn semantics_summary(value: &lattice_tools::OperationSemantics) -> String {
    let mut values = Vec::new();
    if matches!(value.read_only, lattice_tools::SemanticTruth::KnownTrue) {
        values.push("read-only");
    }
    if matches!(value.mutating, lattice_tools::SemanticTruth::KnownTrue) {
        values.push("mutating");
    }
    if matches!(value.destructive, lattice_tools::SemanticTruth::KnownTrue) {
        values.push("destructive");
    }
    if values.is_empty() { "unknown".to_owned() } else { values.join(", ") }
}

fn semantics_table(value: &lattice_tools::OperationSemantics) -> String {
    let json = serde_json::to_value(value).unwrap_or(Value::Null);
    let Some(object) = json.as_object() else {
        return "`unknown`".to_owned();
    };
    let mut output = String::from("| Property | Value |\n| --- | --- |\n");
    for (key, item) in object {
        output.push_str(&format!("| `{}` | `{}` |\n", key, markdown(&item.to_string())));
    }
    output
}

fn error_metadata() -> Vec<(&'static str, bool, &'static str)> {
    ErrorCode::ALL
        .iter()
        .map(|code| (code.code(), code.recoverable(), code.mechanical_action()))
        .collect()
}

fn slug(value: &str) -> String {
    let mut output = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
        } else if !output.ends_with('-') {
            output.push('-');
        }
    }
    output.trim_matches('-').to_owned()
}

fn markdown(value: &str) -> String {
    value.replace('<', "&lt;").replace('>', "&gt;").replace("```", "` ` `")
}

fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n").replace('\r', "\\r")
}
